server:
  port: 8080
spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://postgres:5432/microservices_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
