server:
  port: 8090
spring:
  application:
    name: zuul-service
  cors:
    allowed-origins: "http://192.168.56.55:4200"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
zuul:
  routes:
    users-service:
      path: /students/**
      serviceId: users-service
      stripPrefix: false
    courses-service:
      path: /courses/**
      serviceId: courses-service
      stripPrefix: false
    exams-service:
      path: /exams/**
      serviceId: exams-service
      stripPrefix: false
    answers-service:
      path: /answers/**
      serviceId: answers-service
      stripPrefix: false
  add-proxy-headers: true
