server:
  port: 8090
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
zuul:
  routes:
    users-service:
      path: /students/**
      serviceId: users-service
      stripPrefix: false
    courses-service:
      path: /courses/**
      serviceId: courses-service
      stripPrefix: false  # Ajout ici
    exams-service:
      path: /exams/**
      serviceId: exams-service
      stripPrefix: false
    answers-service:
      path: /answers/**
      serviceId: answers-service
      stripPrefix: false  # Ajout recommandé ici aussi
