server:
  port: 8082
spring:
  application:
    name: exam-service
  datasource:
    url: jdbc:mysql://mysql:3306/microservices_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  web:
    cors:
      allowed-origins: "http://192.168.56.55:4200"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers: "*"
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    appname: exam-service
